spring:
  cloud:
    gateway:
      routes:
      - id: user-svc
        uri: http://localhost:9001/
        predicates:
        - Path=/user/**
        filters:
        - name: UserGatewayFilterFactory
          args:
            baseMessage: Spring Cloud Gateway UserFilter
            preLogger: true
            postLogger: true
      - id: board-svc
        uri: http:://localhost:9002/
        predicates:
        - Path=/board  
        filters:
        - name: BoardGatewayFilterFactory
          args:
            baseMessage: Spring Cloud Gateway BoardFilter
            preLogger: true
            postLogger: true
server:
  port: 9000
