server:
  port: 8081
spring:
  application:
    name: boardservice
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    config:
      name: client
      profile: local
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://saeinlee:1234@localhost:27017/myApp?authSource=admin

  main:
      allow-bean-definition-overriding: true
management:
  endpoint:
    refresh:
      enabled: true