server:
  port: 8081
spring:
  application:
    name: boardservice
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    config:
      name: client
      profile: local
  data:
    mongodb:
      uri: mongodb://root:1234@localhost:27017/mydb
management:
  endpoint:
    refresh:
      enabled: true